include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = WZHelperPrefs

WZHelperPrefs_FILES = WZHelperPrefsRootListController.m
WZHelperPrefs_FRAMEWORKS = UIKit
WZHelperPrefs_PRIVATE_FRAMEWORKS = Preferences
WZHelperPrefs_INSTALL_PATH = /Library/PreferenceBundles
WZHelperPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk

